### ISSUE TITLE
Stale repo for Linux kernel?

### ISSUE THREAD

**Issue by lbmeng** [starfive-tech/beagle_kernel_4.19#3]
This looks like a stale repo as there is a beagle_kernel_5.10 [repo](https://github.com/starfive-tech/beagle_kernel_5.10) here.

If this is no longer needed, please clean it up.

**Comment by pdp7** [comment]
@lbmeng I want this to stay public as it can be useful for beta developers to reference.  There are still functionality that work on in 4.19 and not in 5.10 yet.

The old SDK repo does now point to the Freelight SDK so people are not confused:
https://github.com/starfive-tech/beagle_freedom_u_sdk/blob/starfive/README.md

I want the old uboot 2018 repo to remain public for same reason, but the README now points to Freelight SDK  as well:
https://github.com/starfive-tech/beagle_U_Boot/blob/starfive/README.md
